name: Bunker
version: '${version}'
main: ru.maincraft.bunker.BunkerPlugin
api-version: '1.20'
author: Maincraft
description: Тестовый плагин для экспериментов

commands:
  bunker:
    description: Управление игрой Bunker
    usage: /bunker <create|join|arenas|leave|status|cards|players|open|start|cancel|vote|pass|games|rules|reload|setarena|deletearena|stopall|help>
    permission: bunker.use

permissions:
  bunker.use:
    description: Разрешает использовать команды игрока Bunker
    default: true
  bunker.admin:
    description: Разрешает запускать и сбрасывать игру Bunker
    default: op
    children:
      bunker.use: true
